name: MLflow Project CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  mlflow-pipeline:
    runs-on: ubuntu-latest
    
    env:
      MLFLOW_TRACKING_URI: "file:./mlruns"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'
    
    - name: Check Env
      run: |
        python --version
        pip --version
        
    - name: Install dependencies
      run: |
        pip install -r MLProject/requirements.txt
        pip install imbalanced-learn
        
    - name: Run mlflow project
      run: |
        cd MLProject
        # Run the main modelling script (now CI-aware)
        python modelling.py
        
    - name: Get latest MLflow run_id
      run: |
        cd MLProject
        python -c "
        import os
        import json
        
        # Check if mlruns directory exists
        if os.path.exists('mlruns'):
            # Find the latest run
            experiments = [d for d in os.listdir('mlruns') if d.isdigit()]
            if experiments:
                latest_exp = max(experiments)
                runs_path = f'mlruns/{latest_exp}'
                if os.path.exists(runs_path):
                    runs = [d for d in os.listdir(runs_path) if d != 'meta.yaml']
                    if runs:
                        latest_run = max(runs, key=lambda x: os.path.getctime(f'{runs_path}/{x}'))
                        print(f'Latest MLflow run ID: {latest_run}')
                        
                        # Read run metrics if available
                        metrics_path = f'{runs_path}/{latest_run}/metrics'
                        if os.path.exists(metrics_path):
                            print('Model Metrics:')
                            for metric_file in os.listdir(metrics_path):
                                with open(f'{metrics_path}/{metric_file}', 'r') as f:
                                    lines = f.readlines()
                                    if lines:
                                        value = lines[-1].split()[1]  # Get latest value
                                        print(f'  {metric_file}: {value}')
                    else:
                        print('No runs found')
                else:
                    print('No experiments found')
            else:
                print('MLflow tracking not initialized')
        else:
            print('MLruns directory not found')
        "
    
    - name: Saving artifact to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-run-${{ github.run_id }}
        path: MLProject/mlruns

    - name: Build Docker image
      run: |
        cd MLProject
        docker build -t mlflow-run-itsam77 .

    - name: Tag Docker image
      run: docker tag mlflow-run-${{ github.run_id }} ${{ secrets.DOCKER_USERNAME }}/mlflow-run-${{ github.run_id }}

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-run-${{ github.run_id }}

            
            
        
