name: MLflow Project CI

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  mlflow-pipeline:
    runs-on: ubuntu-latest
    
    # env:
    #   MLFLOW_TRACKING_URI: "file:./mlruns"
    
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'
    
    - name: Check Env
      run: |
        python --version
        pip --version
        
    - name: Install dependencies
      run: |
        pip install -r MLProject/requirements.txt
        pip install imbalanced-learn
        
    - name: Run mlflow project
      run: |
        mlflow run MLmodel --env-manager local
        
    - name: Get latest MLflow run_id
      run: |
        RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Latest run_id: $RUN_ID"
    
    - name: Saving artifact to GitHub Actions
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-run-itsam77
        path: MLProject/mlruns

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "mlflow-run-itsam77"

    - name: Tag Docker image
      run: docker tag mlflow-run-itsam77 ${{ secrets.DOCKER_USERNAME }}/mlflow-run-itsam77


    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-run-itsam77:latest

            
            
        